### ISSUE TITLE
TypeScript?

### ISSUE THREAD

**Issue by DJCordhose** [web-padawan/lit-components#35]
Have you considered doing this in TypeScript? As a first step renaming from js to ts and a bit of tsconfig should do.

**Comment by web-padawan** [comment]
Thanks for the question. Yes, I was thinking about it, although probably not as a first priority.
There might be changes needed to get Karma coverage working with TS, hopefully easy to do.

**Comment by DJCordhose** [comment]
Currently fiddling around to get Karma tests working with TS in another project, 

https://www.npmjs.com/package/karma-typescript 

seems to do the trick for me, will share once I have something running.

**Comment by DJCordhose** [comment]
Ongoing work to keep you up to date about progress

https://github.com/web-padawan/lit-components/pull/36

**Comment by web-padawan** [comment]
Update: we are in progress of switching to TypeScript. All the converted components will use it.
Also there is a set of common mixins written in TS: https://github.com/vaadin/component-mixins
