### ISSUE TITLE
Current state of project

### ISSUE THREAD

**Issue by kr05** [web-padawan/lit-components#37]
Hi there, I'm so excited to have found this repo! What is current state of this project? I have a significant amount of experience with lit-element, in addition to having worked with polymer since polymer 1. Are you looking for a helping hand? I'd be happy to contribute!

**Comment by web-padawan** [comment]
Thanks for the issue. This is a research project which has a goal of estimating an effort needed to rewrite Vaadin components with LitElement, and a possible outcome of such a big refactoring.
I really hope our team will be able to start putting more effort to it later this year.

Until then, I suggest you to look into my personal project, which I have recently released. It is called Aybolit, and there I'm using the experience gained while working on lit-components. 

You can check it here: https://github.com/web-padawan/aybolit

**Comment by web-padawan** [comment]
An update regarding the state: we work on migrating Vaadin components to LitElement.
But we didn't agree on moving to monorepo because of our internal processes.

So this repo is not currently maintained, but individual components repos will be used instead.
